name: Build for MacOS

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o dedupe-music ./dedup-music.go

    # Add a step to check if the file is where it should be
    - name: List files in the directory
      run: ls -alh  # This lists the contents of the current directory

    - name: Upload to GitHub Release
      if: github.event_name == 'release' && github.event.action == 'created'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dedupe-music  # Ensure this path matches the output of the build
        asset_name: dedupe-music_macos
        asset_content_type: application/octet-stream
