name: Build Job
on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          
      - name: Build MacOS ARM64 binary
        run: GOOS=darwin GOARCH=arm64 go build -o dedupe-music
        
      - name: Install Goreleaser
        run: curl -sL https://git.io/goreleaser | bash
        
      - name: Run Goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --snapshot --rm-dist
