name: Build and Release for MacOS

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name
  release:
    types: [created]  # This triggers when a new release is created

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o dedupe-music ./dedup-music.go

    - name: Upload Artifact (for non-release events)
      uses: actions/upload-artifact@v4
      if: github.event_name != 'release'
      with:
        name: dedupe-music_macos
        path: dedupe-music

    - name: Upload Release Asset (for release events)
      uses: actions/upload-release-asset@v1
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dedupe-music
        asset_name: dedupe-music_macos
        asset_content_type: application/octet-stream
