name: Build for MacOS

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name
  release:
    types: [created]
    
jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o dedupe-music ./dedup-music.go

    - name: List files in the directory
      run: ls -alh  # This lists the contents of the current directory

  release:
    name: Release
    runs-on: macos-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the directory
      run: ls -alh  # This lists the contents of the current directory
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dedupe-music_macos
        path: dedupe-music
