name: Build for MacOS

on:
  push:
    branches:
      - main  # or your default branch name
  pull_request:
    branches:
      - main  # or your default branch name
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v -o dedupe-music ./dedup-music.go

    - name: Upload Artifact (Optional)
      uses: actions/upload-artifact@v4
      with:
        name: dedupe-music_macos
        path: dedupe-music

  upload-release-asset:
    name: Upload Release Asset
    runs-on: macos-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dedupe-music
        asset_name: dedupe-music_macos
        asset_content_type: application/octet-stream
